"""initial_schema

Revision ID: 42d67fc3bc0d
Revises:
Create Date: 2026-07-14 12:47:07.495501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import JSONBCompat


revision: str = '42d67fc3bc0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('total_executions', sa.BigInteger(), nullable=True),
    sa.Column('success_executions', sa.BigInteger(), nullable=True),
    sa.Column('failed_executions', sa.BigInteger(), nullable=True),
    sa.Column('retry_executions', sa.BigInteger(), nullable=True),
    sa.Column('total_latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_token_cost', sa.BigInteger(), nullable=True),
    sa.Column('json_failures', sa.BigInteger(), nullable=True),
    sa.Column('schema_failures', sa.BigInteger(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_name')
    )
    op.create_index(op.f('ix_agent_metrics_id'), 'agent_metrics', ['id'], unique=False)
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('input_payload', JSONBCompat(), nullable=True),
    sa.Column('last_output', JSONBCompat(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_id'), 'dead_letters', ['id'], unique=False)
    op.create_index(op.f('ix_dead_letters_resolved'), 'dead_letters', ['resolved'], unique=False)
    op.create_index(op.f('ix_dead_letters_task_id'), 'dead_letters', ['task_id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('issues', JSONBCompat(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('evaluator_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_results_id'), 'evaluation_results', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_results_passed'), 'evaluation_results', ['passed'], unique=False)
    op.create_index(op.f('ix_evaluation_results_task_id'), 'evaluation_results', ['task_id'], unique=False)
    op.create_table('message_dedup_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_message_dedup_records_id'), 'message_dedup_records', ['id'], unique=False)
    op.create_index(op.f('ix_message_dedup_records_task_id'), 'message_dedup_records', ['task_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('payload', JSONBCompat(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lock_owner', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_id'), 'outbox_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_task_id'), 'outbox_events', ['task_id'], unique=False)
    op.create_index('ix_outbox_status_available', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('task_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('input_payload', JSONBCompat(), nullable=True),
    sa.Column('output_payload', JSONBCompat(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'step_id', name='uq_task_step')
    )
    op.create_index(op.f('ix_task_steps_id'), 'task_steps', ['id'], unique=False)
    op.create_index(op.f('ix_task_steps_status'), 'task_steps', ['status'], unique=False)
    op.create_index(op.f('ix_task_steps_task_id'), 'task_steps', ['task_id'], unique=False)
    op.create_table('task_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('step_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('event_status', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', JSONBCompat(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_traces_id'), 'task_traces', ['id'], unique=False)
    op.create_index(op.f('ix_task_traces_task_id'), 'task_traces', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_traces_trace_id'), 'task_traces', ['trace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('target_user', sa.String(length=255), nullable=True),
    sa.Column('selling_points', JSONBCompat(), nullable=True),
    sa.Column('input_payload', JSONBCompat(), nullable=True),
    sa.Column('output_payload', JSONBCompat(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retry', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('last_failure_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_request_id'), 'tasks', ['request_id'], unique=True)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_trace_id'), 'tasks', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_trace_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_request_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_traces_trace_id'), table_name='task_traces')
    op.drop_index(op.f('ix_task_traces_task_id'), table_name='task_traces')
    op.drop_index(op.f('ix_task_traces_id'), table_name='task_traces')
    op.drop_table('task_traces')
    op.drop_index(op.f('ix_task_steps_task_id'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_status'), table_name='task_steps')
    op.drop_index(op.f('ix_task_steps_id'), table_name='task_steps')
    op.drop_table('task_steps')
    op.drop_index('ix_outbox_status_available', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_task_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_message_dedup_records_task_id'), table_name='message_dedup_records')
    op.drop_index(op.f('ix_message_dedup_records_id'), table_name='message_dedup_records')
    op.drop_table('message_dedup_records')
    op.drop_index(op.f('ix_evaluation_results_task_id'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_passed'), table_name='evaluation_results')
    op.drop_index(op.f('ix_evaluation_results_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_dead_letters_task_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_resolved'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_index(op.f('ix_agent_metrics_id'), table_name='agent_metrics')
    op.drop_table('agent_metrics')
    # ### end Alembic commands ###
