"""add_step_executions

Revision ID: fdfd351db815
Revises: 42d67fc3bc0d
Create Date: 2026-07-14 13:03:29.823921
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.types import JSONBCompat


revision: str = 'fdfd351db815'
down_revision: Union[str, None] = '42d67fc3bc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.String(length=64), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_payload', JSONBCompat(), nullable=True),
    sa.Column('output_payload', JSONBCompat(), nullable=True),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_step_execution_task_step', 'step_executions', ['task_id', 'step_id', 'run_number'], unique=True)
    op.create_index(op.f('ix_step_executions_execution_id'), 'step_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_step_executions_status'), 'step_executions', ['status'], unique=False)
    op.create_index(op.f('ix_step_executions_task_id'), 'step_executions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_executions_task_id'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_status'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_execution_id'), table_name='step_executions')
    op.drop_index('ix_step_execution_task_step', table_name='step_executions')
    op.drop_table('step_executions')
    # ### end Alembic commands ###
